### ISSUE TITLE
Any plans for RISCV ?

### ISSUE THREAD

**Issue by gsilos** [keystone-engine/keystone#491]
:-)

**Comment by andy-preston** [comment]
I'm looking for AVR support rather than RiscV but I was just looking at https://github.com/llvm-mirror/llvm/tree/master/lib/Target (which I believe is the basis for https://github.com/keystone-engine/keystone/tree/master/llvm/lib/Target ) and noted that both "your" RiscV and "my" AVR are in there. But, at this stage, I'm not sure if it's trivial to copy from one to the other or if it's a more major undertaking.

**Comment by wtdcode** [comment]
Closed as completed.
